clear
clc
close all

%% ============================================================
% UMAP 2D:
% TRANSICIONES FA -> RS, VENTANAS DE 10 s, 3 MOMENTOS
%
% Comparación:
%   1. FA alejada   : -180 a -170 s antes del retorno a RS
%   2. FA intermedia:  -90 a  -80 s antes del retorno a RS
%   3. FA previa    :  -10 a    0 s antes del retorno a RS
%
% Biomarcadores seleccionados:
%   1. RR_mean
%   2. RMSSD
%   3. pNN20
%   4. pNN50
%   5. CV_RR
%   6. SD2
%   7. SD1/SD2
%   8. DF_completo_Hz
%   9. DF_residual_Hz
%% ============================================================

rng(42)

%% RUTA DE LA TABLA

archivo_tabla = ...
    'C:\Users\Emma\Documents\MATLAB\BIOMARCADORES_10s_FA_A_RS_3ventanas\biomarcadores_transiciones_FA_a_RS_10s_3ventanas.xlsx';

carpeta_salida = fileparts(archivo_tabla);

%% LEER TABLA

if ~isfile(archivo_tabla)

    error('No se encuentra el archivo:\n%s', ...
        archivo_tabla);
end

T = readtable(archivo_tabla);

T.Properties.VariableNames = ...
    matlab.lang.makeValidName(T.Properties.VariableNames);

%% COMPROBAR COLUMNAS OBLIGATORIAS

columnas_obligatorias = { ...
    'ID_transicion', ...
    'Momento', ...
    'Orden_momento'};

for i = 1:numel(columnas_obligatorias)

    if ~ismember( ...
            columnas_obligatorias{i}, ...
            T.Properties.VariableNames)

        error('No se encuentra la columna obligatoria: %s', ...
            columnas_obligatorias{i});
    end
end

%% NORMALIZAR FORMATOS

T.ID_transicion = ...
    strtrim(string(T.ID_transicion));

T.Momento = ...
    strtrim(string(T.Momento));

%% BIOMARCADORES SELECCIONADOS

biomarcadores = { ...
    'RR_mean', ...
    'RMSSD', ...
    'pNN20', ...
    'pNN50', ...
    'CV_RR', ...
    'SD2', ...
    'SD1_SD2', ...
    'DF_completo_Hz', ...
    'DF_residual_Hz'};

%% COMPROBAR QUE LOS BIOMARCADORES EXISTEN

for i = 1:numel(biomarcadores)

    if ~ismember( ...
            biomarcadores{i}, ...
            T.Properties.VariableNames)

        error('No se encuentra la columna: %s', ...
            biomarcadores{i});
    end

    if ~isnumeric(T.(biomarcadores{i}))

        error('La columna %s no es numérica.', ...
            biomarcadores{i});
    end
end

%% CONSERVAR SOLO TRANSICIONES CON LOS TRES MOMENTOS

ids = unique(T.ID_transicion, 'stable');

ids_validos = strings(0,1);

for i = 1:numel(ids)

    id_actual = ids(i);

    idx_id = ...
        T.ID_transicion == id_actual;

    n_alejada = sum( ...
        idx_id & T.Orden_momento == 1);

    n_intermedia = sum( ...
        idx_id & T.Orden_momento == 2);

    n_previa = sum( ...
        idx_id & T.Orden_momento == 3);

    if n_alejada == 1 && ...
            n_intermedia == 1 && ...
            n_previa == 1

        ids_validos(end+1,1) = ...
            id_actual; %#ok<SAGROW>
    end
end

if isempty(ids_validos)

    error(['No se encontraron transiciones con ' ...
        'los tres momentos completos.']);
end

T_umap = T( ...
    ismember(T.ID_transicion, ids_validos), :);

%% CREAR MATRIZ DE DATOS

X = T_umap{:, biomarcadores};

momento = ...
    T_umap.Orden_momento;

id_transicion = ...
    T_umap.ID_transicion;

%% ELIMINAR TRANSICIONES CON NaN O Inf

filas_validas = ...
    all(isfinite(X), 2);

ids_con_datos_validos = unique( ...
    id_transicion(filas_validas), ...
    'stable');

ids_finales = strings(0,1);

for i = 1:numel(ids_con_datos_validos)

    id_actual = ...
        ids_con_datos_validos(i);

    idx_id = ...
        id_transicion == id_actual & ...
        filas_validas;

    n_alejada = sum( ...
        idx_id & momento == 1);

    n_intermedia = sum( ...
        idx_id & momento == 2);

    n_previa = sum( ...
        idx_id & momento == 3);

    if n_alejada == 1 && ...
            n_intermedia == 1 && ...
            n_previa == 1

        ids_finales(end+1,1) = ...
            id_actual; %#ok<SAGROW>
    end
end

idx_final = ...
    ismember(id_transicion, ids_finales) & ...
    filas_validas;

X = X(idx_final, :);

momento = ...
    momento(idx_final);

id_transicion = ...
    id_transicion(idx_final);

if isempty(X)

    error(['No quedan transiciones con ' ...
        'las tres ventanas válidas.']);
end

%% ORDENAR POR TRANSICIÓN Y MOMENTO

Tabla_orden = table( ...
    id_transicion, ...
    momento, ...
    (1:numel(momento))', ...
    'VariableNames', { ...
    'ID_transicion', ...
    'Momento', ...
    'Indice_original'});

Tabla_orden = sortrows( ...
    Tabla_orden, ...
    {'ID_transicion', 'Momento'});

orden = Tabla_orden.Indice_original;

X = X(orden, :);

momento = ...
    momento(orden);

id_transicion = ...
    id_transicion(orden);

%% ÍNDICES DE LOS TRES MOMENTOS

idx1 = momento == 1;
idx2 = momento == 2;
idx3 = momento == 3;

%% MOSTRAR NÚMERO DE OBSERVACIONES

fprintf('\n');
fprintf('============================================\n');
fprintf('UMAP 2D FA -> RS, VENTANAS DE 10 s, 3 MOMENTOS\n');
fprintf('============================================\n');

fprintf('\nTransiciones incluidas en el UMAP:\n');

fprintf('FA alejada     (-180 a -170 s): %d\n', ...
    sum(idx1));

fprintf('FA intermedia  ( -90 a  -80 s): %d\n', ...
    sum(idx2));

fprintf('FA previa      ( -10 a    0 s): %d\n', ...
    sum(idx3));

fprintf('Transiciones completas: %d\n', ...
    numel(ids_finales));

fprintf('Total de puntos: %d\n\n', ...
    size(X,1));

fprintf('Biomarcadores utilizados: %d\n', ...
    numel(biomarcadores));

disp(string(biomarcadores(:)))

%% COMPROBAR VARIABILIDAD

desviaciones = ...
    std(X, 0, 1);

idx_constantes = ...
    desviaciones == 0 | ...
    ~isfinite(desviaciones);

if any(idx_constantes)

    columnas_constantes = ...
        biomarcadores(idx_constantes);

    error('Hay biomarcadores sin variabilidad: %s', ...
        strjoin(columnas_constantes, ', '));
end

%% NORMALIZAR

% Las tres ventanas se normalizan conjuntamente
% para conservar las diferencias entre los momentos.

Xz = zscore(X);

if any(~isfinite(Xz), 'all')

    error(['La matriz normalizada contiene ' ...
        'valores NaN o Inf.']);
end

%% APLICAR UMAP

[reduction, umap_obj] = run_umap( ...
    Xz, ...
    'n_components', 2, ...
    'n_neighbors', 10, ...
    'min_dist', 0.4, ...
    'metric', 'euclidean', ...
    'randomize', false);

if isempty(reduction) || size(reduction,2) < 2

    error('UMAP no ha generado una representación 2D válida.');
end

%% ============================================================
% DISTANCIAS EMPAREJADAS ENTRE LOS TRES MOMENTOS EN UMAP
%% ============================================================

Y = reduction;

ids_unicos = unique(id_transicion,'stable');

dist_1_2 = NaN(numel(ids_unicos),1);  % alejada vs intermedia
dist_1_3 = NaN(numel(ids_unicos),1);  % alejada vs previa
dist_2_3 = NaN(numel(ids_unicos),1);  % intermedia vs previa

for i = 1:numel(ids_unicos)

    id_actual = ids_unicos(i);

    idx_id = id_transicion == id_actual;

    y1 = Y(idx_id & momento == 1,:);
    y2 = Y(idx_id & momento == 2,:);
    y3 = Y(idx_id & momento == 3,:);

    if size(y1,1) == 1 && ...
            size(y2,1) == 1 && ...
            size(y3,1) == 1

        dist_1_2(i) = norm(y1 - y2);
        dist_1_3(i) = norm(y1 - y3);
        dist_2_3(i) = norm(y2 - y3);
    end
end

idx_dist_validas = ...
    isfinite(dist_1_2) & ...
    isfinite(dist_1_3) & ...
    isfinite(dist_2_3);

dist_1_2_validas = dist_1_2(idx_dist_validas);
dist_1_3_validas = dist_1_3(idx_dist_validas);
dist_2_3_validas = dist_2_3(idx_dist_validas);

n_dist_validas = sum(idx_dist_validas);

%% RESUMEN NUMÉRICO DE DISTANCIAS

fprintf('\n============================================\n');
fprintf('DISTANCIAS EMPAREJADAS EN EL ESPACIO UMAP\n');
fprintf('============================================\n');

fprintf('\nDistancia media momento 1 - momento 2: %.4f\n', ...
    mean(dist_1_2_validas,'omitnan'));

fprintf('Distancia media momento 1 - momento 3: %.4f\n', ...
    mean(dist_1_3_validas,'omitnan'));

fprintf('Distancia media momento 2 - momento 3: %.4f\n', ...
    mean(dist_2_3_validas,'omitnan'));

fprintf('\nDistancia mediana momento 1 - momento 2: %.4f\n', ...
    median(dist_1_2_validas,'omitnan'));

fprintf('Distancia mediana momento 1 - momento 3: %.4f\n', ...
    median(dist_1_3_validas,'omitnan'));

fprintf('Distancia mediana momento 2 - momento 3: %.4f\n', ...
    median(dist_2_3_validas,'omitnan'));

%% COMPROBAR HIPÓTESIS PRINCIPAL

% Hipótesis exploratoria:
% Las ventanas alejada e intermedia son más parecidas entre sí que
% respecto a la ventana inmediatamente previa al retorno a RS:
%
%   d(1,2) < d(1,3)
%   d(1,2) < d(2,3)

cumple_hipotesis = ...
    dist_1_2_validas < dist_1_3_validas & ...
    dist_1_2_validas < dist_2_3_validas;

n_cumple = sum(cumple_hipotesis);

porcentaje_cumple = ...
    100 * n_cumple / n_dist_validas;

fprintf('\n--------------------------------------------\n');
fprintf('Hipótesis exploratoria:\n');
fprintf('  d(1,2) < d(1,3) y d(1,2) < d(2,3)\n');

fprintf('\nTransiciones que cumplen la hipótesis: %d / %d (%.1f%%)\n', ...
    n_cumple, ...
    n_dist_validas, ...
    porcentaje_cumple);

%% COMPROBAR EN CUÁNTAS TRANSICIONES LA VENTANA PREVIA ESTÁ MÁS LEJOS

% Momento 3 es la ventana previa al retorno a RS.
% Se considera que la ventana previa está más lejos si:
%
%   d(1,3) > d(1,2)
%   d(2,3) > d(1,2)

previa_mas_lejos = ...
    dist_1_3_validas > dist_1_2_validas & ...
    dist_2_3_validas > dist_1_2_validas;

n_previa_mas_lejos = sum(previa_mas_lejos);

porcentaje_previa_mas_lejos = ...
    100 * n_previa_mas_lejos / n_dist_validas;

fprintf('\nTransiciones en las que la ventana previa ');
fprintf('queda más lejos de las otras dos: %d / %d (%.1f%%)\n', ...
    n_previa_mas_lejos, ...
    n_dist_validas, ...
    porcentaje_previa_mas_lejos);

%% INTERPRETACIÓN AUTOMÁTICA

media_12 = mean(dist_1_2_validas,'omitnan');
media_13 = mean(dist_1_3_validas,'omitnan');
media_23 = mean(dist_2_3_validas,'omitnan');

fprintf('\nConclusión automática:\n');

if media_12 < media_13 && media_12 < media_23

    fprintf(['Las ventanas alejada/intermedia están más próximas entre sí ' ...
        'que respecto a la ventana inmediatamente previa al retorno a RS.\n']);

elseif media_13 < media_12 && media_23 < media_12

    fprintf(['La ventana previa no aparece separada; las distancias hacia ' ...
        'el momento 3 son comparables o incluso menores.\n']);

else

    fprintf(['El patrón de distancias es mixto y no muestra una separación ' ...
        'clara de la ventana previa respecto a las dos ventanas anteriores.\n']);
end

%% GUARDAR TABLA DE DISTANCIAS

Tabla_distancias = table( ...
    ids_unicos(idx_dist_validas), ...
    dist_1_2_validas, ...
    dist_1_3_validas, ...
    dist_2_3_validas, ...
    cumple_hipotesis, ...
    previa_mas_lejos, ...
    'VariableNames', { ...
    'ID_transicion', ...
    'Dist_M1_M2', ...
    'Dist_M1_M3', ...
    'Dist_M2_M3', ...
    'Cumple_hipotesis', ...
    'Previa_mas_lejos'});

archivo_distancias_excel = fullfile( ...
    carpeta_salida, ...
    'Distancias_UMAP_2D_FA_RS_10s_3ventanas.xlsx');

writetable( ...
    Tabla_distancias, ...
    archivo_distancias_excel);

fprintf('\nTabla de distancias guardada en:\n%s\n', ...
    archivo_distancias_excel);

%% ============================================================
% GRÁFICO DE BARRAS DE DISTANCIAS MEDIAS
%% ============================================================

distancias_medias = [ ...
    mean(dist_1_2_validas,'omitnan'), ...
    mean(dist_1_3_validas,'omitnan'), ...
    mean(dist_2_3_validas,'omitnan')];

distancias_sem = [ ...
    std(dist_1_2_validas,'omitnan')/sqrt(sum(isfinite(dist_1_2_validas))), ...
    std(dist_1_3_validas,'omitnan')/sqrt(sum(isfinite(dist_1_3_validas))), ...
    std(dist_2_3_validas,'omitnan')/sqrt(sum(isfinite(dist_2_3_validas)))];

f_dist = figure( ...
    'Color','w', ...
    'Position',[200 200 800 550]);

bar(distancias_medias)

hold on

errorbar( ...
    1:3, ...
    distancias_medias, ...
    distancias_sem, ...
    'k', ...
    'LineStyle','none', ...
    'LineWidth',1.5);

set(gca, ...
    'XTick',1:3, ...
    'XTickLabel',{ ...
    'M1-M2', ...
    'M1-M3', ...
    'M2-M3'}, ...
    'FontSize',14, ...
    'LineWidth',1.1, ...
    'TickDir','out');

ylabel( ...
    'Distancia euclídea en UMAP', ...
    'FontSize',15);

title( ...
    'Distancias entre ventanas en el espacio UMAP', ...
    'FontSize',16, ...
    'FontWeight','normal');

grid on
box on

hold off

archivo_distancias_png = fullfile( ...
    carpeta_salida, ...
    'Distancias_UMAP_2D_FA_RS_10s_3ventanas.png');

drawnow

frame_dist = getframe(f_dist);

imwrite(frame_dist.cdata, archivo_distancias_png);

if ~isfile(archivo_distancias_png)

    error('No se pudo guardar el gráfico de distancias en:\n%s', ...
        archivo_distancias_png);
end

fprintf('Gráfico de distancias guardado en:\n%s\n', ...
    archivo_distancias_png);

%% REPRESENTACIÓN 2D

f = figure( ...
    'Color', 'w', ...
    'Position', [100 100 900 700]);

hold on

scatter( ...
    reduction(idx1,1), ...
    reduction(idx1,2), ...
    85, ...
    [0.00 0.45 0.74], ...
    'filled', ...
    'MarkerEdgeColor', 'k', ...
    'LineWidth', 0.7);

scatter( ...
    reduction(idx2,1), ...
    reduction(idx2,2), ...
    85, ...
    [0.47 0.67 0.19], ...
    'filled', ...
    'MarkerEdgeColor', 'k', ...
    'LineWidth', 0.7);

scatter( ...
    reduction(idx3,1), ...
    reduction(idx3,2), ...
    85, ...
    [0.85 0.33 0.10], ...
    'filled', ...
    'MarkerEdgeColor', 'k', ...
    'LineWidth', 0.7);

xlabel( ...
    'UMAP 1', ...
    'FontSize', 17);

ylabel( ...
    'UMAP 2', ...
    'FontSize', 17);

title( ...
    'UMAP temporal 2D antes del retorno a RS (10 s)', ...
    'FontSize', 17, ...
    'FontWeight', 'normal');

legend( ...
    { ...
    'FA alejada (-180 a -170 s)', ...
    'FA intermedia (-90 a -80 s)', ...
    'FA previa (-10 a 0 s)'}, ...
    'Location', 'best', ...
    'FontSize', 13);

set(gca, ...
    'FontSize', 15, ...
    'LineWidth', 1.1, ...
    'TickDir', 'out');

grid on
box on
axis equal

hold off

%% GUARDAR FIGURA UMAP

archivo_salida = fullfile( ...
    carpeta_salida, ...
    'UMAP_2D_FA_m180_m170_vs_FA_m90_m80_vs_FA_m10_0_RS.png');

drawnow

frame = getframe(f);

imwrite(frame.cdata, archivo_salida);

if ~isfile(archivo_salida)

    error('No se pudo guardar la figura en:\n%s', ...
        archivo_salida);
end

fprintf('\nFigura guardada correctamente en:\n%s\n', ...
    archivo_salida);

fprintf('\nFIN.\n');
